name = "new-portfolio"

compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"                            # This is the variable you'll use in your Worker code
database_name = "portfolio-db"          # Your D1 database name in the Cloudflare dashboard
database_id = "fb28a2a2-ba77-41a4-bc37-53bc526a3043"       # Found in the Cloudflare dashboard